<a href="https://colab.research.google.com/github/majorquev/DBDC_202406_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_01_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com



### 3.2 Matrices

En R, así como en otros lenguajes de programación, una matriz es básicamente un arreglo bi-dimensional, donde las entradas horizontales se entienden como filas y las verticales como columnas. Es posible imaginar una matriz como un arreglo de vectores como columnas (o filas) del mismo largo.

 * ¿Qué se guarda en una matriz?<br>
    Sólo datos de un mismo tipo.
     
 * ¿Cómo se declara una matriz?<br>
    Se puede definir de varias maneras, indicando los elementos que la componen, o combinando vectores como filas o columnas.

 * ¿Cómo se accede a sus elementos?<br>
    Indicando la posición del vector fila, seguido de la posición del vector columna (como es usual).

In [1]:
# 3.2 Matrices ------------
#?matrix de dos filas y 3 columnas, parametros ncol, nrow y byrow
# recibe un vector de elementos
A <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2)
A



[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

In [2]:
B <- matrix(c(1,1,2,3,5,8), ncol = 3, nrow = 2, byrow = T)
B

[,1] [,2] [,3]
[1,] 1    1    2   
[2,] 3    5    8

In [3]:
# clase y atributo dim
class(A)

[1] "matrix" "array"

In [4]:
dim(A)

[1] 2 3

In [5]:
# Genere dos vectores del mismo largo y forme una matriz.

f1 <- c(10,20,30)
f2 <- c(5,6,7)

rbind(f1,f2)



[,1] [,2] [,3]
f1 10   20   30  
f2  5    6    7

In [6]:
cbind(f1,f2)

f1 f2
[1,] 10 5 
[2,] 20 6 
[3,] 30 7

In [ ]:
# funciones cbind() [une vectores como columnas]
# y rbind() [une vectores como filas] (pensadas para matrices)
#?cbind



In [8]:
# NOTA: Podemos añadir una fila/columna a una matriz existente
rbind(A,f1)

[,1] [,2] [,3]
    1    2    5  
    1    3    8  
f1 10   20   30

In [9]:
# si combinamos vectores de distinto largo?
# R recicla valores (recordar explicación)
rbind(A, c(2,4))



Warning message in rbind(A, c(2, 4)):
“number of columns of result is not a multiple of vector length (arg 2)”


[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8   
[3,] 2    4    2

In [10]:
# función diag para la definición de matrices diagonales
#?diag
diag(c(1,3,5,7))



[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    3    0    0   
[3,] 0    0    5    0   
[4,] 0    0    0    7

In [11]:
# Podemos acceder a los elementos de una matriz
# indicando la posición de la fila y la columna de la casilla correspondiente.
# Ejemplo:
A


[,1] [,2] [,3]
[1,] 1    2    5   
[2,] 1    3    8

In [12]:
# quiero rescatar el elemento "(2,3)"
A[2,3]


[1] 8

In [13]:

# CUIDADO:No es lo mismo que
A[c(2,3)] # No es lo que buscamos. Interpreta la matriz como el vector original que la define.

[1] 1 2

In [15]:
# Para acceder a una fila completa
A[2,]

# Para acceder a una columna completa
A[,3]


[1] 1 3 8

[1] 5 8

In [16]:
#Recordemos que podemos actualizar elementos de un vector como:

# quiero cambiar el 3 por un -99 (el 3 de la pos 2,2)
A[2,2] <- -99


In [17]:
A

[,1] [,2] [,3]
[1,] 1      2  5   
[2,] 1    -99  8

In [18]:
# Acceso mediante nombres
M <- rbind(f1,f2)

In [20]:
M

[,1] [,2] [,3]
f1 10   20   30  
f2  5    6    7

In [21]:
# NOTA: Para rescatar los nombres de filas y columnas
rownames(M)
colnames(M)# No hay nombres en las columnas

[1] "f1" "f2"

NULL

In [22]:
colnames(M) <- c("c1","c2","c3")

In [23]:
M

c1 c2 c3
f1 10 20 30
f2  5  6  7

In [26]:
# Acceso mediante nomnbres
# Elemento de la segunda fila tercera columna (2,3)

M["f2","c3"]

[1] 7

In [29]:
# Acceso mediante "indicatrices" lógicas
#Quiero obtener los elementos (1,1) y (2,3) de M
# 1: Crear una matriz de 3x4 con TRUE en dichas posiciones y FALSE en las restantes.
ind2 <- matrix(c(T,F,F,F,F,T) ,ncol = 3, nrow = 2, byrow = T)
ind2

[,1]  [,2]  [,3] 
[1,]  TRUE FALSE FALSE
[2,] FALSE FALSE  TRUE

In [30]:
M[ind2]

[1] 10  7

In [32]:
# Podemos evaluar las casillas de una atriz mediante sentencias lógicas
M[M>=9]

[1] 10 20 30

**Álgebra de matrices**

Las operaciones suma (resta) y ponderación por escalar se llevan cabo mediante los mismos operadores utilizados para valores numéricos y vectores (+,-,*, /). Para multiplicar matrices en cambio, se utiliza el operador %*%, mientras que para invertirlas se utiliza la función solve(), t() para transponer y det() para el cálculo del determinante en el caso de matrices cuadradas.

In [34]:
# transponer una matriz
M
t(M)

c1 c2 c3
f1 10 20 30
f2  5  6  7

f1 f2
c1 10 5 
c2 20 6 
c3 30 7

In [37]:
# 3.2 Álgbra de matrices  ------------
# Ejemplo simple de álgebra de matrices
A+M

c1 c2  c3
f1 11  22 35
f2  6 -93 15

In [38]:
# Multiplicación de matrices
A * M # multiplicación componente a componente


c1 c2   c3 
f1 10   40 150
f2  5 -594  56

In [46]:
t(B) %*% A

[,1] [,2] [,3]
[1,]  4   -295 29  
[2,]  6   -493 45  
[3,] 10   -788 74

In [43]:
# podemos calcular determinantes
# ?det
det(t(B) %*% A)


[1] -1.435296e-12

In [44]:
# Podemos invertir matrices
# ?solve
solve(t(B) %*% A)

ERROR: Error in solve.default(t(B) %*% A): system is computationally singular: reciprocal condition number = 7.40424e-19
