<a href="https://colab.research.google.com/github/majorquev/DBDC_202406_Programacion_en_R_para_ciencia_de_datos/blob/main/Clases/C2/Clase_2_02_listas_y_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Parte 1: Introducción a R (continuación)

**Autor:** Miguel Jorquera Viguera<br>
**E-mail:** majorquev@gmail.com<br>
**Ayudante:** Rodrigo Morales <br>
**E-mail ayudante:** rumorale1@gmail.com


## 5. Listas y Dataframes

### 5.1 Listas

Hasta aquí contamos con dos tipos de objetos para almacenar datos; vectores y matrices. Sin embargo, en ambos casos se tiene la limitante de que no es posible combinar distintos tipos de datos en diferentes entradas. Un objeto que permite una mayor flexibilidad son las listas. En R, una lista es básicamente un arreglo unidimensional, donde en cada entrada es posible almacenar distintos **objetos** (los cuales a su vez pueden almacenar distintos tipos de datos (u otros objetos).
En resumen,

   * ¿Qué son?<br>
    Arreglos unidimensionales que guardan distintos tipos de datos u objetos.<br>

   * ¿Cómo se declaran?<br>
    Se pueden declarar mediante el comando list() o combinando listas existentes. <br>
    
   * ¿Cómo se accede a sus elementos?<br>
    Usando [ ] (retorna lista), o bien usando [ [ ] ] (retorna el objeto).
    En cada caso se puede indicar la posición o nombre del objeto que se quiere rescatar.<br>
    Otra manera es mediante el símbolo $ seguido del nombre del objeto.



In [3]:
# 5. Listas y dataframes ------------
# 5.1 Listas  ------------
# Cómo declarar una lista (comando list() )
#num,letra, pl, mat, lista
l1 <- list(num = c(1,2,3),
           letra = letters,
           mat = diag(1:5),
           subl = list(n=1, pl="hola", v = c(1,5,8)))

l1

$num
[1] 1 2 3

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8

In [4]:
# estructura
str(l1)

List of 4
 $ num  : num [1:3] 1 2 3
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ subl :List of 3
  ..$ n : num 1
  ..$ pl: chr "hola"
  ..$ v : num [1:3] 1 5 8


In [5]:
length(l1)

[1] 4

In [6]:
names(l1)

[1] "num"   "letra" "mat"   "subl"

In [7]:
class(l1)

[1] "list"

In [8]:
# Podemos guardar los objetos en slots con o sin nombres
l2 <- list(3,c(1,7))

In [9]:
l2

[[1]]
[1] 3

[[2]]
[1] 1 7

In [10]:
str(l2)

List of 2
 $ : num 3
 $ : num [1:2] 1 7


In [11]:
# Podemos combinar listas
c(l1,l2)

$num
[1] 1 2 3

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8


[[5]]
[1] 3

[[6]]
[1] 1 7

In [14]:
# Acceso mediante posición
l1[3]

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

In [15]:
class(l1[3])

[1] "list"

In [16]:
l1[2:4]

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8

In [17]:
# NOTA lista[.] retorna un lista con un elemento,
# lista[[.]] retorna el elmento de la lista lista[.]
#Si queremos la matriz de la pos3 y no la lista con la matriz de  la pos 3.
l1[[3]]


[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [18]:
class(l1[[3]])

[1] "matrix" "array"

In [19]:
l1[[3]][4,4]

[1] 4

In [20]:
str(l1)

List of 4
 $ num  : num [1:3] 1 2 3
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ subl :List of 3
  ..$ n : num 1
  ..$ pl: chr "hola"
  ..$ v : num [1:3] 1 5 8


In [23]:
# de la lista l1[[4]], quieo el vector que está en el slot llamado "v" (tercer elemento)
l1[4]#esto es una lista (de largo 1 ) con una lista


$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8

In [24]:
l1[[4]]# Esto es el elemento de la lista l1[4]. Que en este caso corresponde a una lista de largo 3.

$n
[1] 1

$pl
[1] "hola"

$v
[1] 1 5 8

In [26]:
l1[[4]][3]

$v
[1] 1 5 8

In [28]:
l1[[4]][[3]]# Esto es el elemto de la tercera pos de la lista.


[1] 1 5 8

In [29]:
# Acceso mediante nombre
l1["mat"]# lista (de un elemento) con la matriz



$mat
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

In [30]:
l1[["mat"]]# La matriz

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [33]:
str(l1)

List of 4
 $ num  : num [1:3] 1 2 3
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ subl :List of 3
  ..$ n : num 1
  ..$ pl: chr "hola"
  ..$ v : num [1:3] 1 5 8


In [32]:
#Mismo ejemplo de la lista subl
l1[["subl"]][["v"]]


[1] 1 5 8

In [35]:
# acceso vía "$"
l1$mat
# Es equivalente a
l1[["mat"]]
l1[[3]]



[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    2    0    0    0   
[3,] 0    0    3    0    0   
[4,] 0    0    0    4    0   
[5,] 0    0    0    0    5

In [36]:
str(l1)

List of 4
 $ num  : num [1:3] 1 2 3
 $ letra: chr [1:26] "a" "b" "c" "d" ...
 $ mat  : int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ subl :List of 3
  ..$ n : num 1
  ..$ pl: chr "hola"
  ..$ v : num [1:3] 1 5 8


In [38]:
l1$subl$v
# Es lo mismo que
l1[[4]][[3]]
l1[["subl"]][["v"]]

[1] 1 5 8

[1] 1 5 8

[1] 1 5 8

In [40]:
# para saber el largo de la lista/vector

# Para obtener los nombres de la lista

# si quisiéramos renombrar los slots:
names(l1)[3] <- "matriz"
str(l1)

List of 4
 $ num   : num [1:3] 1 2 3
 $ letra : chr [1:26] "a" "b" "c" "d" ...
 $ matriz: int [1:5, 1:5] 1 0 0 0 0 0 2 0 0 0 ...
 $ subl  :List of 3
  ..$ n : num 1
  ..$ pl: chr "hola"
  ..$ v : num [1:3] 1 5 8


In [42]:
# También podemos crear nuevos "slots"
## Indicando nombre en [[]] y luego asignando
l1[["nuevo"]] <- matrix(c(1,2,3,4,5,6), ncol = 3)

In [43]:
l1

$num
[1] 1 2 3

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$matriz
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8


$nuevo
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

In [45]:
## Indicando nombre luego de l1$... y luego asignando
l1$otro <- rep(1,5)

In [46]:
l1

$num
[1] 1 2 3

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$matriz
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8


$nuevo
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

$otro
[1] 1 1 1 1 1

In [48]:
# podemos modificar elementos dentro de un slot
#cambiar el tercer elmento del vector "otro" por un 6.

l1$otro[3] <- 6

In [49]:
l1

$num
[1] 1 2 3

$letra
 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

$matriz
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    2    0    0    0
[3,]    0    0    3    0    0
[4,]    0    0    0    4    0
[5,]    0    0    0    0    5

$subl
$subl$n
[1] 1

$subl$pl
[1] "hola"

$subl$v
[1] 1 5 8


$nuevo
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

$otro
[1] 1 1 6 1 1

### 5.2 Dataframes

Un dataframe es un caso particular de una lista, donde los objetos de cada entrada corresponden a vectores de datos del mismo largo. E este caso cada vector corresponde a una columna del data.frame, mientras que la cantidad de filas corresponde al largo común de los vectores de cada entrada. El objeto resultante es una *tabla*, de ahora en adelante *data.frame*, cuyas columnas poseen distintos tipos de datos entre sí.

 * ¿Cómo se declara un dataframe?<br>
     Mediante la función data.frame(), indicando los vectores que conformarán las columnas.

 * ¿Cómo se accede a los datos de un data.frame?<br>
    Al ser una lista, se puede acceder de la misma manera. Sin embargo también es posible acceder del modo en que se accede a los elementos de una matriz.

In [50]:
# 5.2 Dataframes ----------
# Ejemplo sencillo de definición de un data.frame
# recordar que 1:3 es lo mismo que c(1,2,3)

df <- data.frame(edad = c(25,30,28,35),
                 nombre = c("Miguel", "Danny", "Eduardo", "Kalliba"),
                 rut = c(1,6,3,10))

In [51]:
df

edad nombre  rut
1 25   Miguel   1 
2 30   Danny    6 
3 28   Eduardo  3 
4 35   Kalliba 10

In [52]:
class(df)

[1] "data.frame"

In [53]:
dim(df)

[1] 4 3

In [55]:
# Acceso a columnas de un data.frame
## Igual que en una lista
df$nombre
df[[2]]
df[["nombre"]]


[1] "Miguel"  "Danny"   "Eduardo" "Kalliba"

[1] "Miguel"  "Danny"   "Eduardo" "Kalliba"

[1] "Miguel"  "Danny"   "Eduardo" "Kalliba"

In [57]:
##  Ganamos acceso como matriz
# segunda fila de df
df[2,]

# segunda columna y segunda fila
df[2,2]



edad nombre rut
2 30   Danny  6

[1] "Danny"

In [58]:
df[2,"nombre"]

[1] "Danny"

In [59]:
df

edad nombre  rut
1 25   Miguel   1 
2 30   Danny    6 
3 28   Eduardo  3 
4 35   Kalliba 10

In [61]:
# Rescatar todas las filas donde la edad sea mayor o igual a 30
df[df$edad >= 30,]

edad nombre  rut
2 30   Danny    6 
4 35   Kalliba 10

In [62]:
df[df$edad >= 30, c("edad","rut")]

edad rut
2 30    6 
4 35   10

In [64]:
#Podemos crear nuevas columnas , del mismmo modo que creamos "slots" en una lista
df$tiene_ct <- c(T,F,F,T)

In [65]:
df

edad nombre  rut tiene_ct
1 25   Miguel   1   TRUE   
2 30   Danny    6  FALSE   
3 28   Eduardo  3  FALSE   
4 35   Kalliba 10   TRUE

In [66]:
tiene_mascota <- c("SI","SI","NO","NO")

In [67]:
cbind(df,tiene_mascota)

edad nombre  rut tiene_ct tiene_mascota
1 25   Miguel   1   TRUE    SI           
2 30   Danny    6  FALSE    SI           
3 28   Eduardo  3  FALSE    NO           
4 35   Kalliba 10   TRUE    NO

In [69]:
df <- cbind(df,tiene_mascota)

In [70]:
df

edad nombre  rut tiene_ct tiene_mascota
1 25   Miguel   1   TRUE    SI           
2 30   Danny    6  FALSE    SI           
3 28   Eduardo  3  FALSE    NO           
4 35   Kalliba 10   TRUE    NO

In [72]:
# podemos seleccionar más de una columna a la vez. Ej: seleccionar col1y col3

# Referenciando el nombre de las columnas
df[c(1,3)]# Como si fuese una lista
df[,c(1,3)] # Como si fuese una matriz

edad rut
1 25    1 
2 30    6 
3 28    3 
4 35   10

edad rut
1 25    1 
2 30    6 
3 28    3 
4 35   10

In [ ]:
# Referenciando las posiciones/nombre de las columnas


In [75]:
# Se mantiene la lógica de acceso a los sots de una lista.
df[3]
df[[3]]
df$rut

rut
1  1 
2  6 
3  3 
4 10

[1]  1  6  3 10

[1]  1  6  3 10